-- AlterTable
ALTER TABLE "MetalTransaction"
ADD COLUMN "igstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "sgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "additionalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;